modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="ryoamiclights"
version="${version}"
displayName="RyoamicLights"
displayURL="https://github.com/ThinkingStudios/RyoamicLights"
logoFile= "icon.png"
credits="LambdAurora"
authors="TexTrue, ThinkingStudio"
description='''
LambDynamicLights unofficial architectury port.

Adds dynamic lights to the game.
'''

[[dependencies.ryoamiclights]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ryoamiclights]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.ryoamiclights]]
modId = "obsidianui"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"