modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]]
modId="ryoamiclights"
version="${version}"
displayName="RyoamicLights"
displayURL="https://github.com/ThinkingStudios/LambDynamicLights-Forge"
logoFile= "icon.png"
credits="LambdAurora"
authors="TexTrue, TexTrueStudio"
description='''
LambDynamicLights unofficial forge port.

Adds dynamic lights to the game.
'''

[[dependencies.ryoamiclights]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ryoamiclights]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ryoamiclights]]
modId = "spruceui"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
