name: Build

on: [ pull_request, push, workflow_dispatch ]

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'build.gradle') }}
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Upload artifacts (Forge)
        uses: actions/upload-artifact@v4
        with:
          name: Artifact-Forge
          path: ${{ github.workspace }}/forge/build/libs
      - name: Upload artifacts (Fabric)
        uses: actions/upload-artifact@v4
        with:
          name: Artifact-Fabric
          path: ${{ github.workspace }}/fabric/build/libs
